---
# Namespace containing prometheus deployment
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: prometheus
  name: prometheus
---
# Service account used by Prometheus to connect to Kubernetes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-service-account
  namespace: prometheus
---
# ClusterRole containing permissions needed by Prometheus
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
# ClusterRoleBinding giving necessary permissions to prometheus service account
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-cluster-role
subjects:
- kind: ServiceAccount
  name: prometheus-service-account
  namespace: prometheus
